name: imtools
version: '1.0.0'
summary: Fast image manipulation CLI tool written in Zig
description: |
  A fast, standalone CLI tool for image and wallpaper management.

  Features:
  - Flatten nested image directories
  - Find and remove duplicate images (SHA256)
  - Delete portrait-oriented images
  - Batch convert images to PNG (requires ffmpeg)
  - Download wallpapers from wallhaven.cc
  - AI-powered image sorting via Ollama

  Core commands have no runtime dependencies. Extended features
  require ffmpeg (included) and optionally Ollama (external).

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  imtools:
    command: bin/imtools
    plugs:
      - home
      - removable-media
      - network

parts:
  zig:
    plugin: nil
    override-build: |
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64)
          ZIG_ARCH="x86_64"
          ;;
        arm64)
          ZIG_ARCH="aarch64"
          ;;
        *)
          echo "Unsupported architecture: $CRAFT_ARCH_BUILD_FOR"
          exit 1
          ;;
      esac

      wget -q "https://ziglang.org/download/0.13.0/zig-linux-${ZIG_ARCH}-0.13.0.tar.xz"
      tar xf "zig-linux-${ZIG_ARCH}-0.13.0.tar.xz"
      mkdir -p "$CRAFT_PART_INSTALL/opt/zig"
      cp -r "zig-linux-${ZIG_ARCH}-0.13.0"/* "$CRAFT_PART_INSTALL/opt/zig/"
    build-packages:
      - wget
      - xz-utils

  imtools:
    after: [zig]
    plugin: nil
    source: https://github.com/4cecoder/imtools.git
    source-tag: v1.0.0
    override-build: |
      export PATH="$CRAFT_STAGE/opt/zig:$PATH"
      zig build -Doptimize=ReleaseSafe
      mkdir -p "$CRAFT_PART_INSTALL/bin"
      cp zig-out/bin/imtools "$CRAFT_PART_INSTALL/bin/"

  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
